### ISSUE TITLE
get the img src (url and base64 image)

### ISSUE THREAD

**Issue by juanremi** [kata198/AdvancedHTMLParser#10]
How can i get the src of an image tag (img) using this libary iin two cases:
- when the src is a url
- when the src is a base64 encoded image

thanks

**Comment by kata198** [comment]
Hey,

So to make sure I understand what you are trying to do, here is what I am interpreting:

You have an HTML document with an image inside, and you want to extract the value of the "src" attribute?

So basically, you have something like:

    <img id="myImage" src="hello.jpg" style="width: 150px; height: 150px;" />

And you want to get the string, "hello.jpg" from this element?

Here is an example which will do what I believe to be your aim:

    import AdvancedHTMLParser

    myHtmlStr = '''<div> <img id="myImage" src="hello.jpg" style="width: 150px; height: 150px;" /> </div>'''


    # Instantiate parser
    parser = AdvancedHTMLParser.AdvancedHTMLParser()

    # parse string of HTML
    parser.parseStr(myHtmlStr)

    # Find the referenced img element
    imgEm = parser.getElementById('myImage')

    # Grab the value of the attribute named, "src"
    #   NOTE: You can also access the property "imgEm.src" as "src" is available through dot access as well, per DOM/Javascript standards
    #              You can find all the tag-specific attribute references in AdvancedHTMLParser/constants.py in the "TAG_NAMES_TO_ADDITIONAL_ATTRIBUTES" map
    #              However, AdvancedTag.getAttribute works on all attributes on all tags

    imgSrc = imgEm.getAttribute("src")

    # Ensure it has a value. Will be "None" if not set, or empty string if set to no value
    if imgSrc is None:
        outputText = "Image element does not have 'src' attribute set"
    elif  imgSrc == u'':
        outputText = "Image element has a blank 'src' attribute"
    else:
        outputText = "Image has src attribute as: %s" %( imgSrc, )

    print ( outputText )

Notice the use of "getAttribute"  -- this will fetch the value of any attribute, by property name. So imgEm.getAttribute('src') will return the value of the "src" attribute, or None if not present.

Above example code gives the following output:

$ python test3.py
Image has src attribute as: hello.jpg

If the "src" property is a base64-encoded value, it's the same thing; use getAttribute.

An example of a tag encoded this way is as follows:

    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />

This time .getAttribute("src") will return that whole thing -- "data:image/png;base64,ENCODED_VALUE_HERE"

Changing the above example to redefine *myHtmlStr* as follows:

    myHtmlStr = '''<div> <img id="myImage" src="data:image/png,base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==" style="width: 150px; height: 150px;" /> </div>'''

Yields the following output:

    $ python test4.py
    Image has src attribute as: data:image/png,base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==

Pragmatically, if the src attribute .startswith("data:") is True, then you have a base64 encoded image.

---

Let me know if this covers your questions!

**Comment by juanremi** [comment]
thanks for your reply and your examples, they are all that i need and solve my doubts
